# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d19e7aa1ad54c59dd00653d55d44f045897b3ee1b6c569a828b95fcecd6b742fd54e055b8038fc7deac376d601f2383d99202c761ae840b96b545fed977535b1

test:
  secret_key_base: ebc42d9a2a817e9193e34ca5e8fdb0d9782310c2c2617816a4edc6975d449f013fa946d62849c1e92fb4127855cb5e801143b1fd520bfec319b0f0436b57b02b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
